### ISSUE TITLE
Handle empty mountPropagation field in volume mounts

### ISSUE THREAD

**Issue by rrati** [koki/short#221]
Adding this volume mount to a container:

VolumeMounts: []types.VolumeMount{
  {
    Store:     "name",
    MountPath: "/etc/name",
  }
}

and submitting to kubernetes 1.10 produces the following error:

spec.containers[0].volumeMounts.mountPropagation: Unsupported value: "": supported values: "Bidirectional", "HostToContainer"

It should be possible to define a VolumeMount without having to specify the mount propagation.

**Comment by wlan0** [comment]
Fixed by https://github.com/koki/short/pull/222
