### ISSUE TITLE
Convert_Koki_Secret_to_Kube_v1_Secret is not populating the StringData

### ISSUE THREAD

**Issue by msenmurugan** [koki/short#228]
There is an error in the Convert_Koki_Secret_to_Kube_v1_Secret for the field StringData
https://github.com/koki/short/blob/master/converter/converters/secret.go in line 69, it is 
Actual
kubeSecret.StringData = kubeSecret.StringData
Expected
kubeSecret.StringData = kokiSecret.StringData

Could you pls fix this issue?

**Comment by wlan0** [comment]
Fixed by https://github.com/koki/short/pull/229
