### ISSUE TITLE
The docs site's certificate is expired

### ISSUE THREAD

**Issue by remiovo** [koki/short#236]
Don't know if I should report it here, but the `https://docs.koki.io` site's certificate has expired a month ago.
BTW, thanks for this awesome project.

**Comment by WillBeebe** [comment]
Confirming that the cert is still expired.

**Comment by wlan0** [comment]
@WillBeebe I'm terribly sorry for the delay. I've just updated it. Please check again.

**Comment by WillBeebe** [comment]
Woooo! It's all good, thank you. :) Love this tool btw.
