### ISSUE TITLE
ReplicationController/ReplicaSet Short Syntax

### ISSUE THREAD

**Issue by wlan0** [koki/short#36]
1. Pull Containers to the top level of the rc from inside template.
2. Wrapper key should be either rc or replication_controller (not camel case)
3. The selector and the label inside podTemplateSpec are always expected to match. We can have separate fields for them in case someone has an advanced use case that they need to support, but these fields can be hidden especially since the values ahve to match -
 refer here: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/#pod-selector
4. podLabels/podSelector can just be called selector, and by default we should fill in both selector and spec.template.metadata.label to be something like koki.io/selector.name=$name where $name is the name of the rc, and not show this in the spec. If we are converting from an existing file, then copy the labels into the rc.labels top level key
5. We shouldn't expect the user to specify these selectors when they write rc in short syntax. They should just work by the mechanism described in step 4
6. We should also allow pod imports and in that case, by default copy all the labels from that pod into the rc labels (which on transforming back to k8s puts those labels in both selector and spec.templates.metadata.labels field) 
7. minReadySeconds should convert to ready_seconds
8. Is Status not converted??? 
It should work!!!! 
9. While reverting back to kubernetes type, status should not be printed with zero values if it did not exist in the koki spec file
10. I don't understand why selector is called podSelector in RS, but podLabels in RC. In case of RS, it seems to be a string, wheras in case of RC it seems to be a list of strings. Consistency is needed. Both should have the same name 'selector' and their values should be a list of strings

Also, repeat this for ReplicaSet

**Comment by ublubu** [comment]
Re: Extracting fields from the Pod template to put them directly in RS/RC

I don't think we should do this.
1. I think it makes sense to group all the Pod template concerns in one place. We shouldn't put some pieces of the Pod template in one field and the rest in other fields.
2. We shouldn't pull out every PodSpec/Metadata field. It's easier to read the spec with the replication concerns separated from the template concerns. Also, both RS/RC and Template may contain Annotations (and other metadata fields?), so we'd have some fields with names like "pod_annotations".

**Comment by wlan0** [comment]
We should pull out as many fields up as possible.

Ideally replication_controller should just be a pod definition with a replicas field. This is all it is in its essence.

About the metadata field of pods, the labels and the replication_controller selector should match. Therefore, this can be pulled up into one field at the top level called selectors. Every other metadata field for pod can be encapsulated under another field called pod_metadata
