### ISSUE TITLE
Deployment UX

### ISSUE THREAD

**Issue by wlan0** [koki/short#40]
v1beta1.Deployment is not supported. This should be supported
v1beta2.Deployment is not supported. This should be supported

all of the fields from the different types above should get consolidated into our deployment object. 

containers and other podTemplateSpec fields should be pulled up to the top level key in koki Short syntax

labels within the container should be pulled up into the top level label key (if the values are not the same, that is invalid spec anyways I believe - please verify this)

minReadySeconds should be called min_ready
progressDeadlineSeconds should be called progress_deadline
revisionHistoryLimit should be called max_revs

maxSurge should be called max_extra
maxUnavailable should be extracted from the formula (replicas - parallelism)
(int32) parallelism should be the inverse of maxUnavailable

**Comment by ublubu** [comment]
"max_unavailable" has stronger meaning than "parallelism" in the context of rolling updates. The rest we should do as you've described.
