### ISSUE TITLE
Volume Short syntax

### ISSUE THREAD

**Issue by wlan0** [koki/short#50]
Both VolumeSource and PersistentVolume from various apiGroups (don't know if there is more than 1)

**Comment by ublubu** [comment]
Here's what I'm planning to do for v1.Volume.

From:
```
name: somename
<source-type, e.g. emptyDir>:
  camelField0: val0
  camelField1: val1
```

To:
```
name: somename
type: <snake_case source-type, e.g. empty_dir>
camel_field0: val0
camel_field1: val1
```

**Comment by wlan0** [comment]
sounds ok. I haven't gone throuhg every type to

**Comment by ublubu** [comment]
merged a fix. may revisit later
